### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by Scrymmery** [Ismoh/NoitaMP#101]
**Describe the bug**

**To Reproduce**
1. Start game
2. Click New Game
3. Start server
4. Join server

**Expected behavior**
Ability to see host at least

**Screenshots**
![image](https://user-images.githubusercontent.com/49278078/212097102-48b27749-acda-49e3-8f76-c0ecc8fcbff0.png)

**Desktop (please complete the following information):**
 - OS: [win7]

**Additional context**
when i join my server, my items just disappear, world doesn't sync, and i can't see second me(host). But, on server-side, i see myself, but it just doesn't move. Also can't see NoitaMP menu buttons from your gif on screen corners, only "Hide/Show NoitaMP UI" button.

P.S i see this mod not so popular like noita together, but i just want to test it because of true coop. Maybe it's just don't even playable alpha yet, but even though it looks [playable on your gif](https://media.githubusercontent.com/media/Ismoh/NoitaMP/v2.6.6-alpha%2B1223/misc/2022-06-21_teaser.gif), i can't even try it, am i doing something wrong?

**Comment by Ismoh** [comment]
Hi, thanks for reaching out!
Not sure how familiar you are with GitHub, but masters README.md (startpage - if you want to say so) is not up to date.
NoitaMP is in working progress, that's why you aren't currently able to use it.
[Here](https://github.com/Ismoh/NoitaMP/tree/48-developer-want-to-rework-client-and-server-modulesclasses#noita-multiplayer) you can see the latest README.md, where is a hint, that NoitaMP isn't working yet.
I am working on it round about over one year and someday there will be a **release**.

If you want to be updated, you can join my discord server for notifications.
Unfortunatelly that aren't good news, but that's all I can offer for now.

The gif you can see, is just a teaser. I don't want to release a not working mod. Imagine how the issues would explode.
Please be patient and wait for a **release** and not a **tag**.

**Comment by Ismoh** [comment]
As you can see now, I updated [README.md](https://github.com/Ismoh/NoitaMP/blob/master/README.md)
